### ISSUE TITLE
Issue Installing Sella from Source

### ISSUE THREAD

**Issue by mjohnson541** [zadorlab/sella#16]
When I run `python setup.py install` everything seems to run fine (although it gets unhappy running a check on the dependencies after the install): 

```
copying build/lib.macosx-10.9-x86_64-cpython-310/sella/linalg.py -> build/bdist.macosx-10.9-x86_64/egg/sella
copying build/lib.macosx-10.9-x86_64-cpython-310/sella/hessian_update.py -> build/bdist.macosx-10.9-x86_64/egg/sella
copying build/lib.macosx-10.9-x86_64-cpython-310/sella/samd.py -> build/bdist.macosx-10.9-x86_64/egg/sella
copying build/lib.macosx-10.9-x86_64-cpython-310/sella/peswrapper.py -> build/bdist.macosx-10.9-x86_64/egg/sella
copying build/lib.macosx-10.9-x86_64-cpython-310/sella/eigensolvers.py -> build/bdist.macosx-10.9-x86_64/egg/sella
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/internal.py to internal.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/optimize/optimize.py to optimize.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/optimize/stepper.py to stepper.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/optimize/irc.py to irc.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/optimize/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/optimize/restricted_step.py to restricted_step.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/utilities/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/linalg.py to linalg.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/hessian_update.py to hessian_update.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/samd.py to samd.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/peswrapper.py to peswrapper.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/eigensolvers.py to eigensolvers.cpython-310.pyc
creating stub loader for sella/force_match.cpython-310-darwin.so
creating stub loader for sella/utilities/blas.cpython-310-darwin.so
creating stub loader for sella/utilities/math.cpython-310-darwin.so
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/force_match.py to force_match.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/utilities/blas.py to blas.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sella/utilities/math.py to math.cpython-310.pyc
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying Sella.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying Sella.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying Sella.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying Sella.egg-info/requires.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying Sella.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.9-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
sella.__pycache__.force_match.cpython-310: module references __file__
sella.utilities.__pycache__.blas.cpython-310: module references __file__
sella.utilities.__pycache__.math.cpython-310: module references __file__
creating 'dist/Sella-2.1.0-py3.10-macosx-10.9-x86_64.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing Sella-2.1.0-py3.10-macosx-10.9-x86_64.egg
removing '~/opt/miniconda3/envs/sella/lib/python3.10/site-packages/Sella-2.1.0-py3.10-macosx-10.9-x86_64.egg' (and everything under it)
creating ~/opt/miniconda3/envs/sella/lib/python3.10/site-packages/Sella-2.1.0-py3.10-macosx-10.9-x86_64.egg
Extracting Sella-2.1.0-py3.10-macosx-10.9-x86_64.egg to /Users/mjohns9/opt/miniconda3/envs/sella/lib/python3.10/site-packages
Sella 2.1.0 is already the active version in easy-install.pth

Installed ~/opt/miniconda3/envs/sella/lib/python3.10/site-packages/Sella-2.1.0-py3.10-macosx-10.9-x86_64.egg
Processing dependencies for Sella==2.1.0
Searching for fonttools>=4.22.0
Reading https://pypi.org/simple/fonttools/
/Users/mjohns9/opt/miniconda3/envs/sella/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Downloading https://files.pythonhosted.org/packages/e3/d9/e9bae85e84737e76ebbcbea13607236da0c0699baed0ae4f1151b728a608/fonttools-4.38.0-py3-none-any.whl#sha256=820466f43c8be8c3009aef8b87e785014133508f0de64ec469e4efb643ae54fb
error: Download error for https://files.pythonhosted.org/packages/e3/d9/e9bae85e84737e76ebbcbea13607236da0c0699baed0ae4f1151b728a608/fonttools-4.38.0-py3-none-any.whl#sha256=820466f43c8be8c3009aef8b87e785014133508f0de64ec469e4efb643ae54fb: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
```

However, when I try to import sella from the source directory I get: 
```
>>> import sella
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/code/sella/sella/__init__.py", line 1, in <module>
    from .optimize import IRC, Sella
  File "~/code/sella/sella/optimize/__init__.py", line 1, in <module>
    from .optimize import Sella
  File "~/code/sella/sella/optimize/optimize.py", line 14, in <module>
    from sella.peswrapper import PES, InternalPES
  File "~/code/sella/sella/peswrapper.py", line 12, in <module>
    from sella.utilities.math import modified_gram_schmidt
ModuleNotFoundError: No module named 'sella.utilities.math'
```

**Comment by mjohnson541** [comment]
This is using a conda env built from Sella's environment.yml file that includes cython.

**Comment by ehermes** [comment]
From your logs, it looks like it's trying to import from `~/code/sella/sella/`, which I'm guessing is where you've checked out the repository. But your build log suggests the package was installed into `/Users/mjohns9/opt/miniconda3/envs/sella/lib/python3.10/site-packages`. The compiled Cython files aren't guaranteed to be present in the correct location in your source repository, unless you build the software with something like `python3 setup.py develop --user` (as opposed to `python3 setup.py install --user`).

Try removing the Sella source directory from `$PYTHONPATH` and see if that fixes the problem.

**Comment by ehermes** [comment]
I would highly suggest using `python3 setup.py develop --user` to install the software if you plan on modifying the code, as this essentially creates a symlink between your `site-packages` directory and the source directory, so any Python source changes can be immediately run without re-installing or manually setting any environment variables like `$PYTHONPATH` (the latter approach tends to cause all sorts of issues, especially if you're juggling multiple Python environments a la Conda).
