### ISSUE TITLE
IRC Failing to Converge with IRCInnerLoopConvergenceFailure

### ISSUE THREAD

**Issue by Youbin-K** [zadorlab/sella#20]
Hi, I'm trying to run the IRC in metal slab systems, where it gives me the error of 

sella.optimize.irc.IRCInnerLoopConvergenceFailure

Below is the out file:

****************************************
Running relaxation using VaspInteractive
****************************************
     Step     Time          Energy         fmax
IRC:    0 18:25:51     -166.366325        0.0239
Trying to close the VASP stream but encountered error: 
Traceback (most recent call last):
  File "/gpfs/scratch/ykim219/IRC_test/CCH3/relax_with_VASPInteractive.py", line 51, in run_vasp_interactive
    opt.run(fmax=0.025, steps=1000, direction='forward')
  File "/users/ykim219/.local/lib/python3.9/site-packages/sella/optimize/irc.py", line 101, in run
    for converged in self.irun(fmax, fmax_inner, steps, direction):
sella.optimize.irc.IRCInnerLoopConvergenceFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/ykim219/.local/lib/python3.9/site-packages/vasp_interactive/vasp_interactive.py", line 1015, in _force_kill_process
    self.close()
  File "/users/ykim219/.local/lib/python3.9/site-packages/vasp_interactive/vasp_interactive.py", line 598, in close
    self._run(self.atoms, out=out, require_cell_stdin=False)
vasp_interactive.utils.TimeoutException: Timed out closing VASP process.

Will now force closing the VASP process. The OUTCAR and vasprun.xml outputs may be incomplete
Traceback (most recent call last):
  File "/gpfs/scratch/ykim219/IRC_test/CCH3/relax_with_VASPInteractive.py", line 57, in <module>
    run_vasp_interactive()
  File "/gpfs/scratch/ykim219/IRC_test/CCH3/relax_with_VASPInteractive.py", line 51, in run_vasp_interactive
    opt.run(fmax=0.025, steps=1000, direction='forward')
  File "/users/ykim219/.local/lib/python3.9/site-packages/sella/optimize/irc.py", line 101, in run
    for converged in self.irun(fmax, fmax_inner, steps, direction):
  File "/gpfs/data/cfgoldsm/ykim219/Research/Source_files/ase/ase_3.22.1/ase/optimize/optimize.py", line 135, in irun
    self.step()
  File "/users/ykim219/.local/lib/python3.9/site-packages/sella/optimize/irc.py", line 138, in step
    raise IRCInnerLoopConvergenceFailure
sella.optimize.irc.IRCInnerLoopConvergenceFailure

Would this possibly be due to the compatibility of the VASPinteractive and Sella? Or is this because of the algorithm of the IRC?

**Comment by ehermes** [comment]
This is probably caused by poor gradient precision in the inner loop. Can you try tightening your SCF convergence parameters? It's been a while since I've used VASP so I can't remember which parameters control its SCF convergence threshold...

**Comment by Youbin-K** [comment]
Hi, I tried tightening the SCF convergence parameter from 1e-5 to 1e-6 and 1e-7, which both also fails with the same errors. 
I've also tried to run with increased steps by dx=0.1 to dx=0.3, which also gives the same errors. Would it be worth trying to change the 'eta' value in the IRC and the 'steps' in the forward and reverse directions?

**Comment by Phorbol** [comment]
This Error need to give a smaller dx like 0.05, or give a larger ninner_iter=100

**Comment by levineds** [comment]
I reproduced a constrained-IRC failure on current `master`: forces on frozen atoms were still included in the IRC inner-loop convergence check, even though those force components are outside the free coordinate space. This can produce a false `IRCInnerLoopConvergenceFailure` for slab calculations.

PR #87 projects the inner-loop gradient and logged `fmax` onto the unconstrained subspace and adds regression tests for both ASE `FixAtoms` and native Sella constraints.

@Youbin-K, if you still have this system available, could you retry it with current master (post-PR #87 merge)? If it still fails, the remaining useful diagnostics would be the constraint setup plus the final inner-loop residual using a smaller `dx` and/or larger `ninner_iter`.
